# Generated by Django 4.0.6 on 2022-07-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cosmetics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('ingridients', models.TextField()),
                ('price', models.FloatField()),
                ('rank', models.FloatField()),
                ('combination', models.CharField(max_length=4)),
                ('normal', models.CharField(max_length=4)),
                ('dry', models.CharField(max_length=4)),
                ('oily', models.CharField(max_length=4)),
                ('sensitive', models.CharField(max_length=4)),
            ],
        ),
    ]
